<?php
/**
 * Turns selected Coder Army sheet problems into auto-graded compiler exercises:
 * adds a precise stdin/stdout statement, starter code, and test cases to the
 * EXISTING problem (matched by topic+title → slug).
 *
 * Each entry carries a `reference` Python solution used ONLY by
 * database/seed/verify_compiler.php to prove the expected outputs are correct.
 * The reference is never stored in the database.
 */

$arrStarters = [
    'php' => "<?php\n\$n = (int) trim(fgets(STDIN));\n\$a = \$n ? array_map('intval', preg_split('/\\s+/', trim(fgets(STDIN)))) : [];\n\n// TODO: solve and print the answer\n",
    'python' => "n = int(input())\na = list(map(int, input().split())) if n else []\n\n# TODO: solve and print the answer\n",
    'cpp' => "#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin >> n;\n    vector<long long> a(n);\n    for (auto& x : a) cin >> x;\n    // TODO: solve and print the answer\n    return 0;\n}\n",
    'java' => "import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        long[] a = new long[n];\n        for (int i = 0; i < n; i++) a[i] = sc.nextLong();\n        // TODO: solve and print the answer\n    }\n}\n",
];
$intStarter = [
    'php' => "<?php\n\$n = (int) trim(fgets(STDIN));\n\n// TODO: print the answer\n",
    'python' => "n = int(input())\n\n# TODO: print the answer\n",
    'cpp' => "#include <bits/stdc++.h>\nusing namespace std;\nint main(){ long long n; cin >> n; /* TODO */ return 0; }\n",
    'java' => "import java.util.*;\npublic class Main{ public static void main(String[] x){ long n=new Scanner(System.in).nextLong(); /* TODO */ } }\n",
];
$strStarter = [
    'php' => "<?php\n\$s = rtrim(fgets(STDIN), \"\\r\\n\");\n\n// TODO: print the answer\n",
    'python' => "s = input()\n\n# TODO: print the answer\n",
    'cpp' => "#include <bits/stdc++.h>\nusing namespace std;\nint main(){ string s; getline(cin,s); /* TODO */ return 0; }\n",
    'java' => "import java.util.*;\npublic class Main{ public static void main(String[] x){ String s=new Scanner(System.in).nextLine(); /* TODO */ } }\n",
];

return [
    [
        'topic' => 'Array', 'title' => 'Search an Element in an array',
        'statement_md' => "Line 1: `n`. Line 2: `n` integers. Line 3: target `x`. Print the **index (0-based)** of the first occurrence of `x`, or `-1`.",
        'examples_md' => "```\nInput:\n4\n10 20 30 40\n30\nOutput:\n2\n```",
        'starters' => [
            'php' => "<?php\n\$n = (int) trim(fgets(STDIN));\n\$a = array_map('intval', preg_split('/\\s+/', trim(fgets(STDIN))));\n\$x = (int) trim(fgets(STDIN));\n\n// TODO: print the first index of \$x in \$a, or -1\n",
            'python' => "n = int(input())\na = list(map(int, input().split()))\nx = int(input())\n\n# TODO: print the first index of x in a, or -1\n",
            'cpp' => "#include <bits/stdc++.h>\nusing namespace std;\nint main(){ int n; cin>>n; vector<int> a(n); for(auto&v:a)cin>>v; int x; cin>>x; /* TODO */ return 0; }\n",
            'java' => "import java.util.*;\npublic class Main{ public static void main(String[] z){ Scanner s=new Scanner(System.in); int n=s.nextInt(); int[] a=new int[n]; for(int i=0;i<n;i++)a[i]=s.nextInt(); int x=s.nextInt(); /* TODO */ } }\n",
        ],
        'reference' => "n=int(input())\na=list(map(int,input().split()))\nx=int(input())\nprint(a.index(x) if x in a else -1)",
        'tests' => [
            ['stdin' => "4\n10 20 30 40\n30", 'expected' => "2", 'sample' => true],
            ['stdin' => "4\n10 20 30 40\n99", 'expected' => "-1", 'sample' => true],
            ['stdin' => "5\n5 4 3 2 1\n5", 'expected' => "0"],
            ['stdin' => "1\n7\n7", 'expected' => "0"],
        ],
    ],
    [
        'topic' => 'Array', 'title' => 'Find minimum and maximum element in an array',
        'statement_md' => "Line 1: `n`. Line 2: `n` integers. Print the minimum and maximum separated by a space: `min max`.",
        'examples_md' => "```\nInput:\n5\n3 7 1 9 2\nOutput:\n1 9\n```",
        'starters' => $arrStarters,
        'reference' => "n=int(input())\na=list(map(int,input().split()))\nprint(min(a), max(a))",
        'tests' => [
            ['stdin' => "5\n3 7 1 9 2", 'expected' => "1 9", 'sample' => true],
            ['stdin' => "1\n42", 'expected' => "42 42", 'sample' => true],
            ['stdin' => "4\n-5 -1 -9 -3", 'expected' => "-9 -1"],
        ],
    ],
    [
        'topic' => 'Array', 'title' => 'Cyclically rotate an array by one',
        'statement_md' => "Line 1: `n`. Line 2: `n` integers. Rotate the array right by one (last element moves to front) and print it space-separated.",
        'examples_md' => "```\nInput:\n5\n1 2 3 4 5\nOutput:\n5 1 2 3 4\n```",
        'starters' => $arrStarters,
        'reference' => "n=int(input())\na=list(map(int,input().split()))\nif a:\n    a=[a[-1]]+a[:-1]\nprint(' '.join(map(str,a)))",
        'tests' => [
            ['stdin' => "5\n1 2 3 4 5", 'expected' => "5 1 2 3 4", 'sample' => true],
            ['stdin' => "3\n7 8 9", 'expected' => "9 7 8", 'sample' => true],
            ['stdin' => "1\n4", 'expected' => "4"],
        ],
    ],
    [
        'topic' => 'Array', 'title' => 'Sort an array of 0s, 1s and 2s',
        'statement_md' => "Line 1: `n`. Line 2: `n` integers (each 0, 1, or 2). Print the array sorted in non-decreasing order, space-separated.",
        'examples_md' => "```\nInput:\n6\n2 0 2 1 1 0\nOutput:\n0 0 1 1 2 2\n```",
        'starters' => $arrStarters,
        'reference' => "n=int(input())\na=list(map(int,input().split()))\na.sort()\nprint(' '.join(map(str,a)))",
        'tests' => [
            ['stdin' => "6\n2 0 2 1 1 0", 'expected' => "0 0 1 1 2 2", 'sample' => true],
            ['stdin' => "3\n2 1 0", 'expected' => "0 1 2", 'sample' => true],
            ['stdin' => "4\n1 1 1 1", 'expected' => "1 1 1 1"],
        ],
    ],
    [
        'topic' => 'Array', 'title' => 'Majority Element',
        'statement_md' => "Line 1: `n`. Line 2: `n` integers, where one element appears **more than n/2 times**. Print that element.",
        'examples_md' => "```\nInput:\n7\n2 2 1 1 1 2 2\nOutput:\n2\n```",
        'starters' => $arrStarters,
        'reference' => "n=int(input())\na=list(map(int,input().split()))\ncand=None;c=0\nfor x in a:\n    if c==0: cand=x\n    c += 1 if x==cand else -1\nprint(cand)",
        'tests' => [
            ['stdin' => "7\n2 2 1 1 1 2 2", 'expected' => "2", 'sample' => true],
            ['stdin' => "5\n3 3 3 1 2", 'expected' => "3", 'sample' => true],
            ['stdin' => "1\n9", 'expected' => "9"],
        ],
    ],
    [
        'topic' => 'String', 'title' => 'Reverse a String',
        'statement_md' => "Read a line of text and print it reversed.",
        'examples_md' => "```\nInput:  hello\nOutput: olleh\n```",
        'starters' => $strStarter,
        'reference' => "s=input()\nprint(s[::-1])",
        'tests' => [
            ['stdin' => "hello", 'expected' => "olleh", 'sample' => true],
            ['stdin' => "DSA Learn", 'expected' => "nraeL ASD", 'sample' => true],
            ['stdin' => "x", 'expected' => "x"],
        ],
    ],
    [
        'topic' => 'String', 'title' => 'Palindrome String',
        'statement_md' => "Read a string. Print `YES` if it is a palindrome, otherwise `NO`.",
        'examples_md' => "```\nInput:  racecar\nOutput: YES\n```",
        'starters' => $strStarter,
        'reference' => "s=input()\nprint('YES' if s==s[::-1] else 'NO')",
        'tests' => [
            ['stdin' => "racecar", 'expected' => "YES", 'sample' => true],
            ['stdin' => "hello", 'expected' => "NO", 'sample' => true],
            ['stdin' => "a", 'expected' => "YES"],
            ['stdin' => "abba", 'expected' => "YES"],
        ],
    ],
    [
        'topic' => 'Searching and Sorting', 'title' => 'Bubble Sort',
        'statement_md' => "Line 1: `n`. Line 2: `n` integers. Print them sorted ascending, space-separated.",
        'examples_md' => "```\nInput:\n5\n5 2 8 1 9\nOutput:\n1 2 5 8 9\n```",
        'starters' => $arrStarters,
        'reference' => "n=int(input())\na=list(map(int,input().split()))\nprint(' '.join(map(str,sorted(a))))",
        'tests' => [
            ['stdin' => "5\n5 2 8 1 9", 'expected' => "1 2 5 8 9", 'sample' => true],
            ['stdin' => "3\n3 2 1", 'expected' => "1 2 3", 'sample' => true],
            ['stdin' => "4\n-1 5 -3 0", 'expected' => "-3 -1 0 5"],
        ],
    ],
    [
        'topic' => 'Searching and Sorting', 'title' => 'Quick Sort',
        'statement_md' => "Line 1: `n`. Line 2: `n` integers. Print them sorted ascending, space-separated.",
        'examples_md' => "```\nInput:\n5\n5 2 8 1 9\nOutput:\n1 2 5 8 9\n```",
        'starters' => $arrStarters,
        'reference' => "n=int(input())\na=list(map(int,input().split()))\nprint(' '.join(map(str,sorted(a))))",
        'tests' => [
            ['stdin' => "5\n5 2 8 1 9", 'expected' => "1 2 5 8 9", 'sample' => true],
            ['stdin' => "6\n9 8 7 6 5 4", 'expected' => "4 5 6 7 8 9", 'sample' => true],
            ['stdin' => "1\n0", 'expected' => "0"],
        ],
    ],
    [
        'topic' => 'Searching and Sorting', 'title' => 'Square root of a number',
        'statement_md' => "Read a non-negative integer `n`. Print the floor of its square root (the largest integer `r` with `r*r ≤ n`).",
        'examples_md' => "```\nInput:  16\nOutput: 4\n```",
        'starters' => $intStarter,
        'reference' => "import math\nn=int(input())\nprint(math.isqrt(n))",
        'tests' => [
            ['stdin' => "16", 'expected' => "4", 'sample' => true],
            ['stdin' => "10", 'expected' => "3", 'sample' => true],
            ['stdin' => "1", 'expected' => "1"],
            ['stdin' => "0", 'expected' => "0"],
            ['stdin' => "100", 'expected' => "10"],
        ],
    ],
    [
        'topic' => 'Searching and Sorting', 'title' => 'Searching an element in a sorted array',
        'statement_md' => "Line 1: `n`. Line 2: `n` integers in **non-decreasing** order. Line 3: target `x`. Print the index (0-based) of `x`, or `-1`. Aim for O(log n).",
        'examples_md' => "```\nInput:\n5\n-1 0 3 5 9\n5\nOutput:\n3\n```",
        'starters' => [
            'php' => "<?php\n\$n=(int)trim(fgets(STDIN));\n\$a=array_map('intval',preg_split('/\\s+/',trim(fgets(STDIN))));\n\$x=(int)trim(fgets(STDIN));\n\n// TODO: binary search; print index or -1\n",
            'python' => "n=int(input())\na=list(map(int,input().split()))\nx=int(input())\n\n# TODO: binary search; print index or -1\n",
            'cpp' => "#include <bits/stdc++.h>\nusing namespace std;\nint main(){ int n; cin>>n; vector<int> a(n); for(auto&v:a)cin>>v; int x; cin>>x; /* TODO */ return 0; }\n",
            'java' => "import java.util.*;\npublic class Main{ public static void main(String[] z){ Scanner s=new Scanner(System.in); int n=s.nextInt(); int[] a=new int[n]; for(int i=0;i<n;i++)a[i]=s.nextInt(); int x=s.nextInt(); /* TODO */ } }\n",
        ],
        'reference' => "import bisect\nn=int(input())\na=list(map(int,input().split()))\nx=int(input())\ni=bisect.bisect_left(a,x)\nprint(i if i<len(a) and a[i]==x else -1)",
        'tests' => [
            ['stdin' => "5\n-1 0 3 5 9\n5", 'expected' => "3", 'sample' => true],
            ['stdin' => "5\n-1 0 3 5 9\n2", 'expected' => "-1", 'sample' => true],
            ['stdin' => "1\n4\n4", 'expected' => "0"],
        ],
    ],
    [
        'topic' => 'Dynamic Programming', 'title' => 'Nth Fibonacci Number',
        'statement_md' => "Read `n`. Print the n-th Fibonacci number where `fib(0)=0`, `fib(1)=1`.",
        'examples_md' => "```\nInput:  10\nOutput: 55\n```",
        'starters' => $intStarter,
        'reference' => "n=int(input())\na,b=0,1\nfor _ in range(n): a,b=b,a+b\nprint(a)",
        'tests' => [
            ['stdin' => "10", 'expected' => "55", 'sample' => true],
            ['stdin' => "0", 'expected' => "0", 'sample' => true],
            ['stdin' => "1", 'expected' => "1"],
            ['stdin' => "7", 'expected' => "13"],
        ],
    ],
    [
        'topic' => 'Dynamic Programming', 'title' => "Kadane's Algorithm",
        'statement_md' => "Line 1: `n`. Line 2: `n` integers. Print the maximum sum of any non-empty contiguous subarray.",
        'examples_md' => "```\nInput:\n9\n-2 1 -3 4 -1 2 1 -5 4\nOutput:\n6\n```",
        'starters' => $arrStarters,
        'reference' => "n=int(input())\na=list(map(int,input().split()))\nbest=cur=a[0]\nfor x in a[1:]:\n    cur=max(x,cur+x); best=max(best,cur)\nprint(best)",
        'tests' => [
            ['stdin' => "9\n-2 1 -3 4 -1 2 1 -5 4", 'expected' => "6", 'sample' => true],
            ['stdin' => "3\n1 2 3", 'expected' => "6", 'sample' => true],
            ['stdin' => "3\n-1 -2 -3", 'expected' => "-1"],
            ['stdin' => "1\n5", 'expected' => "5"],
        ],
    ],
    [
        'topic' => 'Dynamic Programming', 'title' => 'House Robber',
        'statement_md' => "Line 1: `n`. Line 2: `n` non-negative integers (house values). Print the maximum total you can rob without robbing two adjacent houses.",
        'examples_md' => "```\nInput:\n5\n2 7 9 3 1\nOutput:\n12\n```",
        'starters' => $arrStarters,
        'reference' => "n=int(input())\na=list(map(int,input().split())) if n else []\nprev=cur=0\nfor x in a:\n    prev,cur=cur,max(cur,prev+x)\nprint(cur)",
        'tests' => [
            ['stdin' => "5\n2 7 9 3 1", 'expected' => "12", 'sample' => true],
            ['stdin' => "4\n1 2 3 1", 'expected' => "4", 'sample' => true],
            ['stdin' => "1\n5", 'expected' => "5"],
            ['stdin' => "4\n2 1 1 2", 'expected' => "4"],
        ],
    ],
    [
        'topic' => 'Greedy', 'title' => 'Minimum number of jumps',
        'statement_md' => "Line 1: `n`. Line 2: `n` non-negative integers; `a[i]` is the max jump length from index `i`. Print the minimum jumps to reach the last index, or `-1` if unreachable.",
        'examples_md' => "```\nInput:\n5\n2 3 1 1 4\nOutput:\n2\n```",
        'starters' => $arrStarters,
        'reference' => "n=int(input())\na=list(map(int,input().split()))\nif n<=1:\n    print(0)\nelif a[0]==0:\n    print(-1)\nelse:\n    jumps=1;far=a[0];end=a[0];ans=-1;ok=True\n    for i in range(1,n):\n        if i==n-1:\n            ans=jumps;ok=False;break\n        far=max(far,i+a[i])\n        if i==end:\n            jumps+=1;end=far\n            if i>=end:\n                ans=-1;ok=False;break\n    print(ans if not ok else -1)",
        'tests' => [
            ['stdin' => "5\n2 3 1 1 4", 'expected' => "2", 'sample' => true],
            ['stdin' => "4\n1 1 1 1", 'expected' => "3", 'sample' => true],
            ['stdin' => "2\n0 1", 'expected' => "-1"],
            ['stdin' => "1\n0", 'expected' => "0"],
        ],
    ],
    [
        'topic' => 'Hashing', 'title' => 'Longest consecutive subsequence',
        'statement_md' => "Line 1: `n`. Line 2: `n` integers. Print the length of the longest run of consecutive integers (order in the array does not matter).",
        'examples_md' => "```\nInput:\n6\n100 4 200 1 3 2\nOutput:\n4\n```",
        'starters' => $arrStarters,
        'reference' => "n=int(input())\na=list(map(int,input().split())) if n else []\ns=set(a);best=0\nfor x in s:\n    if x-1 not in s:\n        y=x\n        while y+1 in s: y+=1\n        best=max(best,y-x+1)\nprint(best)",
        'tests' => [
            ['stdin' => "6\n100 4 200 1 3 2", 'expected' => "4", 'sample' => true],
            ['stdin' => "10\n0 3 7 2 5 8 4 6 0 1", 'expected' => "9", 'sample' => true],
            ['stdin' => "1\n5", 'expected' => "1"],
        ],
    ],

    [
        'topic' => 'Array', 'title' => 'Missing number',
        'statement_md' => "Line 1: `n`. Line 2: `n-1` distinct integers from the range `1..n` (one is missing). Print the missing number.",
        'examples_md' => "```\nInput:\n5\n1 2 4 5\nOutput:\n3\n```",
        'starters' => $arrStarters,
        'reference' => "n=int(input())\na=list(map(int,input().split()))\nprint(n*(n+1)//2 - sum(a))",
        'tests' => [
            ['stdin' => "5\n1 2 4 5", 'expected' => "3", 'sample' => true],
            ['stdin' => "3\n1 3", 'expected' => "2", 'sample' => true],
            ['stdin' => "4\n1 2 3", 'expected' => "4"],
            ['stdin' => "2\n2", 'expected' => "1"],
        ],
    ],
    [
        'topic' => 'Array', 'title' => 'Count Primes',
        'statement_md' => "Read `n`. Print the count of prime numbers **strictly less than** `n`.",
        'examples_md' => "```\nInput:  10\nOutput: 4\n```",
        'starters' => $intStarter,
        'reference' => "n=int(input())\nif n<3:\n    print(0)\nelse:\n    s=[True]*n; s[0]=s[1]=False\n    for i in range(2,int(n**0.5)+1):\n        if s[i]:\n            for j in range(i*i,n,i): s[j]=False\n    print(sum(s))",
        'tests' => [
            ['stdin' => "10", 'expected' => "4", 'sample' => true],
            ['stdin' => "0", 'expected' => "0", 'sample' => true],
            ['stdin' => "2", 'expected' => "0"],
            ['stdin' => "20", 'expected' => "8"],
        ],
    ],
    [
        'topic' => 'Array', 'title' => 'Equilibrium Point',
        'statement_md' => "Line 1: `n`. Line 2: `n` integers. Print the **1-based** index `i` where the sum of elements before `i` equals the sum after `i`, or `-1`.",
        'examples_md' => "```\nInput:\n5\n1 3 5 2 2\nOutput:\n3\n```",
        'starters' => $arrStarters,
        'reference' => "n=int(input())\na=list(map(int,input().split()))\ntotal=sum(a);left=0;ans=-1\nfor i in range(n):\n    if left==total-left-a[i]:\n        ans=i+1;break\n    left+=a[i]\nprint(ans)",
        'tests' => [
            ['stdin' => "5\n1 3 5 2 2", 'expected' => "3", 'sample' => true],
            ['stdin' => "1\n99", 'expected' => "1", 'sample' => true],
            ['stdin' => "2\n1 2", 'expected' => "-1"],
        ],
    ],
    [
        'topic' => 'String', 'title' => 'Length of Last Word',
        'statement_md' => "Read a line of text. Print the length of the last word (words are separated by spaces).",
        'examples_md' => "```\nInput:  Hello World\nOutput: 5\n```",
        'starters' => $strStarter,
        'reference' => "s=input()\nw=s.split()\nprint(len(w[-1]) if w else 0)",
        'tests' => [
            ['stdin' => "Hello World", 'expected' => "5", 'sample' => true],
            ['stdin' => "DSA", 'expected' => "3", 'sample' => true],
            ['stdin' => "fly me   to the moon", 'expected' => "4"],
        ],
    ],
    [
        'topic' => 'String', 'title' => 'Roman Number to Integer',
        'statement_md' => "Read a Roman numeral (uppercase) and print its integer value.",
        'examples_md' => "```\nInput:  MCMXCIV\nOutput: 1994\n```",
        'starters' => $strStarter,
        'reference' => "s=input().strip()\nm={'I':1,'V':5,'X':10,'L':50,'C':100,'D':500,'M':1000}\ntotal=0\nfor i,c in enumerate(s):\n    if i+1<len(s) and m[c]<m[s[i+1]]: total-=m[c]\n    else: total+=m[c]\nprint(total)",
        'tests' => [
            ['stdin' => "III", 'expected' => "3", 'sample' => true],
            ['stdin' => "IV", 'expected' => "4", 'sample' => true],
            ['stdin' => "LVIII", 'expected' => "58"],
            ['stdin' => "MCMXCIV", 'expected' => "1994"],
        ],
    ],
    [
        'topic' => 'String', 'title' => 'Longest Distinct characters in string',
        'statement_md' => "Read a string. Print the length of the longest substring without repeating characters.",
        'examples_md' => "```\nInput:  abcabcbb\nOutput: 3\n```",
        'starters' => $strStarter,
        'reference' => "s=input()\nseen={};left=0;best=0\nfor r,c in enumerate(s):\n    if c in seen and seen[c]>=left: left=seen[c]+1\n    seen[c]=r; best=max(best,r-left+1)\nprint(best)",
        'tests' => [
            ['stdin' => "abcabcbb", 'expected' => "3", 'sample' => true],
            ['stdin' => "bbbb", 'expected' => "1", 'sample' => true],
            ['stdin' => "pwwkew", 'expected' => "3"],
            ['stdin' => "abcd", 'expected' => "4"],
        ],
    ],
    [
        'topic' => 'Searching and Sorting', 'title' => 'Floor in a Sorted Array',
        'statement_md' => "Line 1: `n`. Line 2: `n` integers in non-decreasing order. Line 3: `x`. Print the **index (0-based)** of the floor of `x` (largest element ≤ `x`), or `-1`.",
        'examples_md' => "```\nInput:\n7\n1 2 8 10 11 12 19\n5\nOutput:\n1\n```",
        'starters' => [
            'php' => "<?php\n\$n=(int)trim(fgets(STDIN));\n\$a=array_map('intval',preg_split('/\\s+/',trim(fgets(STDIN))));\n\$x=(int)trim(fgets(STDIN));\n\n// TODO: print index of floor(x) or -1\n",
            'python' => "n=int(input())\na=list(map(int,input().split()))\nx=int(input())\n\n# TODO: print index of floor(x) or -1\n",
            'cpp' => "#include <bits/stdc++.h>\nusing namespace std;\nint main(){ int n; cin>>n; vector<int> a(n); for(auto&v:a)cin>>v; int x; cin>>x; /* TODO */ return 0; }\n",
            'java' => "import java.util.*;\npublic class Main{ public static void main(String[] z){ Scanner s=new Scanner(System.in); int n=s.nextInt(); int[] a=new int[n]; for(int i=0;i<n;i++)a[i]=s.nextInt(); int x=s.nextInt(); /* TODO */ } }\n",
        ],
        'reference' => "import bisect\nn=int(input())\na=list(map(int,input().split()))\nx=int(input())\ni=bisect.bisect_right(a,x)-1\nprint(i if i>=0 else -1)",
        'tests' => [
            ['stdin' => "7\n1 2 8 10 11 12 19\n5", 'expected' => "1", 'sample' => true],
            ['stdin' => "7\n1 2 8 10 11 12 19\n0", 'expected' => "-1", 'sample' => true],
            ['stdin' => "4\n1 2 3 4\n4", 'expected' => "3"],
            ['stdin' => "3\n2 3 5\n10", 'expected' => "2"],
        ],
    ],
    [
        'topic' => 'Dynamic Programming', 'title' => 'Print first n Fibonacci Numbers',
        'statement_md' => "Read `n` (n ≥ 1). Print the first `n` Fibonacci numbers starting `0 1`, space-separated.",
        'examples_md' => "```\nInput:  5\nOutput: 0 1 1 2 3\n```",
        'starters' => $intStarter,
        'reference' => "n=int(input())\nf=[];a,b=0,1\nfor _ in range(n): f.append(a); a,b=b,a+b\nprint(' '.join(map(str,f)))",
        'tests' => [
            ['stdin' => "5", 'expected' => "0 1 1 2 3", 'sample' => true],
            ['stdin' => "1", 'expected' => "0", 'sample' => true],
            ['stdin' => "7", 'expected' => "0 1 1 2 3 5 8"],
            ['stdin' => "2", 'expected' => "0 1"],
        ],
    ],
    [
        'topic' => 'Dynamic Programming', 'title' => 'Count number of hops',
        'statement_md' => "A frog can hop 1, 2, or 3 steps at a time. Read `n` and print the number of distinct ways to reach the n-th step. (1 ≤ n ≤ 30)",
        'examples_md' => "```\nInput:  4\nOutput: 7\n```",
        'starters' => $intStarter,
        'reference' => "n=int(input())\ndp=[0]*(n+1);dp[0]=1\nfor i in range(1,n+1):\n    dp[i]=dp[i-1]+(dp[i-2] if i>=2 else 0)+(dp[i-3] if i>=3 else 0)\nprint(dp[n])",
        'tests' => [
            ['stdin' => "1", 'expected' => "1", 'sample' => true],
            ['stdin' => "2", 'expected' => "2", 'sample' => true],
            ['stdin' => "3", 'expected' => "4"],
            ['stdin' => "4", 'expected' => "7"],
        ],
    ],
    [
        'topic' => 'Dynamic Programming', 'title' => 'Count numbers containing 4',
        'statement_md' => "Read `n`. Print how many integers in the range `[1, n]` contain the digit `4`.",
        'examples_md' => "```\nInput:  50\nOutput: 14\n```",
        'starters' => $intStarter,
        'reference' => "n=int(input())\nprint(sum(1 for i in range(1,n+1) if '4' in str(i)))",
        'tests' => [
            ['stdin' => "10", 'expected' => "1", 'sample' => true],
            ['stdin' => "4", 'expected' => "1", 'sample' => true],
            ['stdin' => "50", 'expected' => "14"],
            ['stdin' => "44", 'expected' => "9"],
        ],
    ],
    [
        'topic' => 'Greedy', 'title' => 'Assign Cookies',
        'statement_md' => "Line 1: children's greed factors (space-separated). Line 2: cookie sizes (space-separated). A child is content if given a cookie of size ≥ their greed. Print the maximum number of content children.",
        'examples_md' => "```\nInput:\n1 2 3\n1 1\nOutput:\n1\n```",
        'starters' => [
            'php' => "<?php\n\$g=array_map('intval',preg_split('/\\s+/',trim(fgets(STDIN))));\n\$s=array_map('intval',preg_split('/\\s+/',trim(fgets(STDIN))));\n\n// TODO: print number of content children\n",
            'python' => "g=list(map(int,input().split()))\ns=list(map(int,input().split()))\n\n# TODO: print number of content children\n",
            'cpp' => "#include <bits/stdc++.h>\nusing namespace std;\nint main(){ /* read two lines of ints */ return 0; }\n",
            'java' => "import java.util.*;\npublic class Main{ public static void main(String[] a){ Scanner s=new Scanner(System.in); /* read two lines */ } }\n",
        ],
        'reference' => "g=list(map(int,input().split()))\ns=list(map(int,input().split()))\ng.sort();s.sort()\ni=j=0\nwhile i<len(g) and j<len(s):\n    if s[j]>=g[i]: i+=1\n    j+=1\nprint(i)",
        'tests' => [
            ['stdin' => "1 2 3\n1 1", 'expected' => "1", 'sample' => true],
            ['stdin' => "1 2\n1 2 3", 'expected' => "2", 'sample' => true],
            ['stdin' => "10 9 8 7\n5 6 7 8", 'expected' => "2"],
        ],
    ],
    [
        'topic' => 'Greedy', 'title' => 'Can Place Flowers',
        'statement_md' => "Line 1: the flowerbed as `0`/`1` values (space-separated; 1 = planted). Line 2: integer `k`. Print `true` if `k` new flowers can be planted so that no two are adjacent, else `false`.",
        'examples_md' => "```\nInput:\n1 0 0 0 1\n1\nOutput:\ntrue\n```",
        'starters' => [
            'php' => "<?php\n\$bed=array_map('intval',preg_split('/\\s+/',trim(fgets(STDIN))));\n\$k=(int)trim(fgets(STDIN));\n\n// TODO: print 'true' or 'false'\n",
            'python' => "bed=list(map(int,input().split()))\nk=int(input())\n\n# TODO: print 'true' or 'false'\n",
            'cpp' => "#include <bits/stdc++.h>\nusing namespace std;\nint main(){ /* read bed line + k */ return 0; }\n",
            'java' => "import java.util.*;\npublic class Main{ public static void main(String[] a){ /* read bed + k */ } }\n",
        ],
        'reference' => "bed=list(map(int,input().split()))\nk=int(input())\ncount=0;i=0;m=len(bed)\nwhile i<m:\n    if bed[i]==0 and (i==0 or bed[i-1]==0) and (i==m-1 or bed[i+1]==0):\n        bed[i]=1;count+=1\n    i+=1\nprint('true' if count>=k else 'false')",
        'tests' => [
            ['stdin' => "1 0 0 0 1\n1", 'expected' => "true", 'sample' => true],
            ['stdin' => "1 0 0 0 1\n2", 'expected' => "false", 'sample' => true],
            ['stdin' => "0 0 0\n2", 'expected' => "true"],
            ['stdin' => "0\n1", 'expected' => "true"],
        ],
    ],
    [
        'topic' => 'Heaps', 'title' => 'Minimum Cost of ropes',
        'statement_md' => "Line 1: `n`. Line 2: `n` rope lengths. Repeatedly connect two ropes at a cost equal to their sum, until one rope remains. Print the minimum total cost.",
        'examples_md' => "```\nInput:\n4\n4 3 2 6\nOutput:\n29\n```",
        'starters' => $arrStarters,
        'reference' => "import heapq\nn=int(input())\na=list(map(int,input().split()))\nheapq.heapify(a)\ncost=0\nwhile len(a)>1:\n    x=heapq.heappop(a);y=heapq.heappop(a)\n    cost+=x+y;heapq.heappush(a,x+y)\nprint(cost)",
        'tests' => [
            ['stdin' => "4\n4 3 2 6", 'expected' => "29", 'sample' => true],
            ['stdin' => "1\n5", 'expected' => "0", 'sample' => true],
            ['stdin' => "3\n1 2 3", 'expected' => "9"],
            ['stdin' => "2\n1 2", 'expected' => "3"],
        ],
    ],
    [
        'topic' => 'Hashing', 'title' => 'First Repeating element',
        'statement_md' => "Line 1: `n`. Line 2: `n` integers. Print the **1-based** index of the first element that appears more than once (smallest index among repeating elements), or `-1`.",
        'examples_md' => "```\nInput:\n7\n1 5 3 4 3 5 6\nOutput:\n2\n```",
        'starters' => $arrStarters,
        'reference' => "from collections import Counter\nn=int(input())\na=list(map(int,input().split()))\nc=Counter(a);ans=-1\nfor i,x in enumerate(a):\n    if c[x]>1: ans=i+1;break\nprint(ans)",
        'tests' => [
            ['stdin' => "7\n1 5 3 4 3 5 6", 'expected' => "2", 'sample' => true],
            ['stdin' => "4\n1 2 3 4", 'expected' => "-1", 'sample' => true],
            ['stdin' => "5\n1 1 2 3 4", 'expected' => "1"],
        ],
    ],
    [
        'topic' => 'Hashing', 'title' => 'First element to occur k times',
        'statement_md' => "Line 1: `n` and `k`. Line 2: `n` integers. Print the first element that occurs **exactly** `k` times, or `-1`.",
        'examples_md' => "```\nInput:\n5 2\n1 7 4 3 4\nOutput:\n4\n```",
        'starters' => [
            'php' => "<?php\n[\$n,\$k]=array_map('intval',preg_split('/\\s+/',trim(fgets(STDIN))));\n\$a=array_map('intval',preg_split('/\\s+/',trim(fgets(STDIN))));\n\n// TODO: print first element occurring exactly k times, or -1\n",
            'python' => "n,k=map(int,input().split())\na=list(map(int,input().split()))\n\n# TODO: print first element occurring exactly k times, or -1\n",
            'cpp' => "#include <bits/stdc++.h>\nusing namespace std;\nint main(){ int n,k; cin>>n>>k; vector<int> a(n); for(auto&v:a)cin>>v; /* TODO */ return 0; }\n",
            'java' => "import java.util.*;\npublic class Main{ public static void main(String[] z){ Scanner s=new Scanner(System.in); int n=s.nextInt(),k=s.nextInt(); int[] a=new int[n]; for(int i=0;i<n;i++)a[i]=s.nextInt(); /* TODO */ } }\n",
        ],
        'reference' => "from collections import Counter\nn,k=map(int,input().split())\na=list(map(int,input().split()))\nc=Counter(a);ans=-1\nfor x in a:\n    if c[x]==k: ans=x;break\nprint(ans)",
        'tests' => [
            ['stdin' => "5 2\n1 7 4 3 4", 'expected' => "4", 'sample' => true],
            ['stdin' => "5 1\n1 7 4 3 4", 'expected' => "1", 'sample' => true],
            ['stdin' => "4 2\n1 2 3 4", 'expected' => "-1"],
        ],
    ],
    [
        'topic' => 'Array', 'title' => 'Subarray with given sum',
        'statement_md' => "Line 1: `n` and `S`. Line 2: `n` positive integers. Print the **1-based** start and end indices of the first contiguous subarray summing to `S` (space-separated), or `-1`.",
        'examples_md' => "```\nInput:\n5 12\n1 2 3 7 5\nOutput:\n2 4\n```",
        'starters' => [
            'php' => "<?php\n[\$n,\$S]=array_map('intval',preg_split('/\\s+/',trim(fgets(STDIN))));\n\$a=array_map('intval',preg_split('/\\s+/',trim(fgets(STDIN))));\n\n// TODO: print '1-based l r' or -1\n",
            'python' => "n,S=map(int,input().split())\na=list(map(int,input().split()))\n\n# TODO: print '1-based l r' or -1\n",
            'cpp' => "#include <bits/stdc++.h>\nusing namespace std;\nint main(){ long long n,S; cin>>n>>S; vector<long long> a(n); for(auto&v:a)cin>>v; /* TODO */ return 0; }\n",
            'java' => "import java.util.*;\npublic class Main{ public static void main(String[] z){ Scanner s=new Scanner(System.in); long n=s.nextLong(),S=s.nextLong(); long[] a=new long[(int)n]; for(int i=0;i<n;i++)a[i]=s.nextLong(); /* TODO */ } }\n",
        ],
        'reference' => "n,S=map(int,input().split())\na=list(map(int,input().split()))\nl=0;cur=0;res=-1\nfor r in range(n):\n    cur+=a[r]\n    while cur>S and l<r:\n        cur-=a[l];l+=1\n    if cur==S:\n        res=(l+1,r+1);break\nprint(f'{res[0]} {res[1]}' if res!=-1 else -1)",
        'tests' => [
            ['stdin' => "5 12\n1 2 3 7 5", 'expected' => "2 4", 'sample' => true],
            ['stdin' => "5 15\n1 2 3 4 5", 'expected' => "1 5", 'sample' => true],
            ['stdin' => "3 100\n1 2 3", 'expected' => "-1"],
        ],
    ],
];
